---
- name: setup web application
  hosts: webservers
  remote_user: vagrant

  tasks:
    - name: install python packages
      become: yes
      apt:
        pkg:
          - python3-pip
        state: latest
        update-cache: true
    - name: copy app files
      copy:
        src: ../app/
        dest: ~/app/
        owner: vagrant
        mode: "0755"
    - name: start application
      shell: |
        cd ~/app
        pip install -r requirements.txt
        nohup python3 app.py &
